### PR TITLE
Parse SORT statement

### PR DESCRIPTION
**Pull request by Claes65**

### CODE REVIEW

**Comment by MarkusAmshove** [comment]
I assert them one by one.
e.g.
```
assertThat(sort.operands().get(0))...
assertThat(sort.operands().get(1))...
```

**Comment by MarkusAmshove** [comment]
I've got the following new diagnostic:

```
/***********************************************************************
DEFINE SUBROUTINE SUBROUTINE-NAME
/***********************************************************************

END-ALL
SORT BY #VAR1

BEFORE BREAK PROCESSING
   IGNORE
END-BEFORE
END-SORT

END-SUBROUTINE
```
grafik

If I remove the
```
BEFORE BREAK PROCESSING
   IGNORE
END-BEFORE
```

then it works again.

Can you have a look at that? `BEFORE BREAK` is already implemented, so I would expect this to work correctly.

I don't see an obvious change from you causing this, so it might be introduced now because `SORT` is actually being parsed

**Comment by Claes65** [comment]
Sure 👌 
Also, why does the BEFORE BREAK not pass correctly? It should expect END-BEFORE, not END-BREAK.

**Comment by MarkusAmshove** [comment]
My guess is that the `BEFORE` is somehow consumed so that it starts at `BREAK` for a new statement, which is an indication for `AT BREAK OF`

**Comment by MarkusAmshove** [comment]
```
END-ALL
SORT BY #VAR1
BEFORE BREAK PROCESSING
IGNORE
END-SORT
```
this is a smaller repro, it already tries to parse `AT BREAK`

**Comment by Claes65** [comment]
Hmm, weird. I can’t think of anything I do with BEFORE. could it be the sequence of the statements in outer switch?

**Comment by Claes65** [comment]
It's because IsOperand() returns true for BEFORE, as canBeIdentifier() returns true. For BREAK it returns false.
I could set BEFORE to false as well in the SK table, but:
**BEFORE(true, false, false), // TODO: Should be false, but is currently used by NatUnit**

**Comment by MarkusAmshove** [comment]
I will do it in a separate PR, so that it is properly blamable in git :-)

**Pull request merged**
