### PR TITLE
Implement experimental async initialization

### PR DESCRIPTION
**Pull request by MarkusAmshove**

### CODE REVIEW

**Comment by Claes65** [comment]
@MarkusAmshove 
.peek(f -> monitor.progress("Parsing data areas %s".formatted(f.getReferableName())))  ->
.peek(f -> monitor.progress("Parsing data areas %s".formatted(f.getReferableName()),0))
in NaturalLanguageService.java line 439.

**Comment by MarkusAmshove** [comment]
@Claes65 when not passing a percentage it increases it automatically: https://github.com/MarkusAmshove/natls/pull/409/files#diff-b9da325b6c2b2cd99f4d5fdc3e89b8a65b46d0cd8309d21a23c204b5b30d3c5aR21

it might not pass the threshold for the message based percentage on that step though, but I don't see that as a problem

**Comment by Claes65** [comment]
> @Claes65 when not passing a percentage it increases it automatically: https://github.com/MarkusAmshove/natls/pull/409/files#diff-b9da325b6c2b2cd99f4d5fdc3e89b8a65b46d0cd8309d21a23c204b5b30d3c5aR21
> 
> it might not pass the threshold for the message based percentage on that step though, but I don't see that as a problem. Unless I'm missing something :)

Not sure - but it hung up Eclipse when 0 was not mentioned. I guess too many messages is sent without the 0 (as 0 means nothing is sent it seems).

**Comment by MarkusAmshove** [comment]
I'll change it to either not exceeding 100% or not increasing it at all for message based stuff

**Comment by MarkusAmshove** [comment]
@Claes65 should be resolved in current main branch :)

**Pull request merged**
