### PR TITLE
Support mainframe specific not sign ¬

### PR DESCRIPTION
**Pull request by awilkins**
This is a valid negative comparator on mainframe and is replaced by `^=` on LUW

- [Unix](https://documentation.softwareag.com/natux/9.3.1/en/webhelp/natux-webhelp/pg/pg_furth_lcc.htm?hi=logical+logically+condition+conditions+criteria#x346)
- [Mainframe](https://documentation.softwareag.com/natural/natux/pg/pg_furth_lcc.htm#x346)

Should have all behaviours that caret-equals has on LUW

(not sure if `¬` on it's own is a legal character ... but not sure of that for `^` either)

### CODE REVIEW

**Comment by MarkusAmshove** [comment]
Thank you for the contribution :-)
If you're unfamiliar with SonarQube (SonarCloud) feel free to ping me and I'll tell you why it is complaining.

**Comment by awilkins** [comment]
Naah, I'm familiar ... I'm still not even sure that `¬` on it's own is a valid sequence (except probably in variable names because Natural is insane).

**Comment by MarkusAmshove** [comment]
Looking at the [documentation](https://documentation.softwareag.com/natmf/9.2.2/en/webhelp/natmf-webhelp/pg/pg_furth_lcc.htm), especially at [Logical Operators in Complex Logical Expressions ](https://documentation.softwareag.com/natmf/9.2.2/en/webhelp/natmf-webhelp/pg/pg_furth_lcc.htm#Log_Operators_CLE), `¬` is not allowed instead of `NOT` (for e.g. `NOT FALSE`).

I also can't find it for [variable or object names](https://documentation.softwareag.com/natural/nat921unx/webhelp/natux-webhelp/using/use_rules.htm).

The docs have been wrong quiet a few times in the past though :-) 
I'd probably take `¬` on its own out and add it later if needed.

You could also add your `case ` above the [default case](https://github.com/MarkusAmshove/natls/blob/main/libs/natparse/src/main/java/org/amshove/natparse/lexing/Lexer.java#L319) and let it fall through to the default case when not also encountering the `=`. That way you get a diagnostic.
You can then run `gradlew fatJar` in the repository and run the linter CLI in your natural project and filter for the specific diagnostic id:
`java -jar /path/to/natls-repo/libs/natlint/build/libs/natlint.jar -d "NPL001" -xlint` 
That will only print diagnostics with that id (`-xlint` is to skip linting and only do lexing/parsing, to save some time).

**Comment by awilkins** [comment]
Thanks for the help, and sorry for the long wait for me to pay some attention. Hopefully I'll have some more patches soon.

**Pull request merged**
