### PR TITLE
Parse MOVE statement

### PR DESCRIPTION
**Pull request by Claes65**

### CODE REVIEW

**Comment by Claes65** [comment]
Code analysis step is halted, it seems @MarkusAmshove

**Comment by MarkusAmshove** [comment]
Can you push a new commit to this? Can't seem to get it running, it must not process it on their side

**Comment by Claes65** [comment]
Adding MOVE (AD=), will push soon :)

**Comment by Claes65** [comment]
Made changes to abstractParser(), please review @MarkusAmshove

**Pull request merged**
